remove go as dependency and ignore if snap does not work

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -78,25 +78,6 @@ if [ -n "${INSTALL_DEPENDENCIES}" ]; then
          direnv \
          stow
 
-    # install go
-    GO_VERSION="1.17.4"
-    if [[ ! -d "${HOME}/.local/etc/go/${GO_VERSION}" ]]; then
-        (
-            echo -e "${__COLOR_INFO}INFO: Installing go${__COLOR_RESET}"
-            mkdir -p "/tmp/go"
-            cd "/tmp/go"
-            curl -O "https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz"
-            tar -xvf "go${GO_VERSION}.linux-amd64.tar.gz"
-            mkdir -p "${HOME}/.local/etc/go"
-            mv "go" "${HOME}/.local/etc/go/${GO_VERSION}"
-        )
-    fi
-
-    echo -e "${__COLOR_INFO}INFO: Make go available in PATH${__COLOR_RESET}"
-    [[ -f "${HOME}/.local/bin/go" ]] && rm "${HOME}/.local/bin/go"
-    ln -s "${HOME}/.local/etc/go/${GO_VERSION}/bin/go" "${HOME}/.local/bin/go"
-    mkdir -p "${HOME}/.go"
-
     # install dependencies for emacs
     sudo apt install -y \
          okular \
@@ -118,10 +99,9 @@ if [ -n "${INSTALL_DEPENDENCIES}" ]; then
          ripgrep \
          fd-find
 
-    sudo snap install ccls --classic
-
-    # Install go dependencies like this, for example
-    # go install github.com/shurcooL/markdownfmt@latest
+    # try to install snap dependencies. Note that this is not working
+    # for Docker or WSL. Ignore if it fails
+    sudo snap install ccls --classic || true
 fi
 
 #------------------------------------------------------------------------------#
